name: Run Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

      - name: Install Google Chrome version 115
        run: |
          wget -q -O google-chrome-stable_115.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_115.0.5790.170-1_amd64.deb
          sudo apt install -y ./google-chrome-stable_115.deb

      - name: Verify Chrome install
        run: google-chrome --version

      - name: Install dependencies (Python packages)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-html selenium webdriver-manager

      - name: Run tests
        run: pytest test_cases --html=report.html



